import React, { useState, useMemo } from 'react';
import { 
    Paper, Box, Typography, IconButton, Grid, TextField, FormControl, InputLabel, 
    Select, MenuItem, Button, Table, TableHead, TableBody, TableRow, 
    Chip, Dialog, DialogTitle, DialogContent, DialogActions, Tooltip,
    List, ListItem, ListItemText, Stack, Divider,
    Autocomplete, InputAdornment, LinearProgress, Avatar, TableCell
} from '@mui/material';
import { Project, RFI, UserRole, RFIStatus, ScheduleTask } from '../types';
import { 
    Plus, Eye, Edit2, History, X, ShieldCheck, FileText, Printer, 
    Clock, Lock, CheckCircle2, XCircle, FileSearch, CalendarPlus, 
    Link as LinkIcon, ExternalLink, Calendar, MapPin, BarChart2,
    MessageSquare, User as UserIcon, Circle, Filter, CheckCircle, Trash2
} from 'lucide-react';
import StatCard from './StatCard';

interface Props {
  project: Project;
  userRole: UserRole;
  onProjectUpdate: (project: Project) => void;
}

const RFIModule: React.FC<Props> = ({ project, userRole, onProjectUpdate }) => {
    const [viewMode, setViewMode] = useState<'LIST' | 'UPDATE'>('LIST');
    const [formData, setFormData] = useState<Partial<RFI>>({});
    const [locationError, setLocationError] = useState<string | null>(null);
    const [selectedRfiForDetail, setSelectedRfiForDetail] = useState<RFI | null>(null);
    const [isDetailModalOpen, setIsDetailModalOpen] = useState(false);
    const [taskFilter, setTaskFilter] = useState<string>('all');
    
    // Additional fields for RFI form
    const [inspectionTime, setInspectionTime] = useState('');
    const [inspectionPurpose, setInspectionPurpose] = useState<'First' | 'Second' | 'Third' | 'Routine' | 'Special'>('First');
    const [inspectionReport, setInspectionReport] = useState('');
    const [engineerComments, setEngineerComments] = useState('');
    const [areSignature, setAreSignature] = useState('');
    const [iowSignature, setIowSignature] = useState('');
    const [meSltSignature, setMeSltSignature] = useState('');
    const [reSignature, setReSignature] = useState('');
    const [requestNumber, setRequestNumber] = useState('');
    const [workingDrawings, setWorkingDrawings] = useState<string[]>([]);

    const statusCounts = {
        [RFIStatus.OPEN]: project.rfis.filter(r => r.status === RFIStatus.OPEN).length,
        [RFIStatus.APPROVED]: project.rfis.filter(r => r.status === RFIStatus.APPROVED).length,
        [RFIStatus.REJECTED]: project.rfis.filter(r => r.status === RFIStatus.REJECTED).length,
        [RFIStatus.CLOSED]: project.rfis.filter(r => r.status === RFIStatus.CLOSED).length,
    };

    const filteredRFIs = useMemo(() => {
        return [...project.rfis]
            .filter(r => taskFilter === 'all' || r.linkedTaskId === taskFilter)
            .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
    }, [project.rfis, taskFilter]);

    const validateLocation = (loc: string): boolean => {
        // Standard Road Chainage format: [Numbers]+[3 digits] [Side]
        // Matches patterns like: 12+400 RHS, 0+005 LHS, 102+900 Both
        const regex = /^\d+\+\d{3}\s+(LHS|RHS|Both|Both Sides|L|R)$/i;
        if (!loc) return false;
        return regex.test(loc.trim());
    };

    const handleCreate = () => {
        setFormData({
            rfiNumber: `RFI-${Date.now().toString().slice(-6)}`,
            status: RFIStatus.OPEN,
            date: new Date().toISOString().split('T')[0],
            inspectionPurpose: 'First',
            workflowLog: [{ 
                stage: 'Created', 
                user: userRole, 
                timestamp: new Date().toISOString(), 
                comments: 'Initial request generated by field team.' 
            }]
        });
        setLocationError(null);
        setViewMode('UPDATE');
        
        // Reset additional fields
        setInspectionTime('');
        setInspectionPurpose('First');
        setInspectionReport('');
        setEngineerComments('');
        setAreSignature('');
        setIowSignature('');
        setMeSltSignature('');
        setReSignature('');
        setRequestNumber('');
        setWorkingDrawings([]);
    };

    const handleEdit = (rfi: RFI) => {
        setFormData(rfi);
        setLocationError(null);
        setViewMode('UPDATE');
        
        // Set additional fields
        setInspectionTime(rfi.inspectionTime || '');
        setInspectionPurpose(rfi.inspectionPurpose || 'First');
        setInspectionReport(rfi.inspectionReport || '');
        setEngineerComments(rfi.engineerComments || '');
        setAreSignature(rfi.areSignature || '');
        setIowSignature(rfi.iowSignature || '');
        setMeSltSignature(rfi.meSltSignature || '');
        setReSignature(rfi.reSignature || '');
        setRequestNumber(rfi.requestNumber || '');
        setWorkingDrawings(rfi.workingDrawings || []);
    };

    const handleSave = () => {
        if (!formData.description || !formData.location) return;

        if (!validateLocation(formData.location)) {
            setLocationError("Required format: 'Chainage + Side' (e.g., 12+400 RHS)");
            return;
        }

        const now = new Date().toISOString();
        const existingRfi = project.rfis.find(r => r.id === formData.id);
        let updatedLog = [...(formData.workflowLog || [])];

        if (existingRfi && existingRfi.status !== formData.status) {
            updatedLog.push({
                stage: formData.status,
                user: userRole,
                timestamp: now,
                comments: `Status transitioned from ${existingRfi.status} to ${formData.status}.`
            });
        }

        const newRFI: RFI = {
            id: formData.id || `rfi-${Date.now()}`,
            rfiNumber: formData.rfiNumber || `RFI-${Date.now()}`,
            date: formData.date!,
            location: formData.location!,
            description: formData.description!,
            status: formData.status || RFIStatus.OPEN,
            requestedBy: formData.requestedBy || userRole,
            inspectionDate: formData.inspectionDate || '',
            inspectionTime: inspectionTime,
            inspectionPurpose: inspectionPurpose,
            inspectionReport: inspectionReport,
            engineerComments: engineerComments,
            areSignature: areSignature,
            iowSignature: iowSignature,
            meSltSignature: meSltSignature,
            reSignature: reSignature,
            requestNumber: requestNumber,
            workingDrawings: workingDrawings,
            submittedBy: formData.submittedBy,
            receivedBy: formData.receivedBy,
            submittedDate: formData.submittedDate,
            receivedDate: formData.receivedDate,
            workflowLog: updatedLog,
            linkedTaskId: formData.linkedTaskId
        };

        const updatedRFIs = formData.id 
            ? project.rfis.map(r => r.id === formData.id ? newRFI : r)
            : [...project.rfis, newRFI];

        onProjectUpdate({ ...project, rfis: updatedRFIs });
        setViewMode('LIST');
        setFormData({}); // Reset form
    };

    const handleDelete = (rfiId: string) => {
        if (window.confirm('Are you sure you want to delete this RFI?')) {
            const updatedRFIs = project.rfis.filter(r => r.id !== rfiId);
            onProjectUpdate({ ...project, rfis: updatedRFIs });
        }
    };

    const getStageIcon = (stage: string) => {
        switch (stage.toLowerCase()) {
            case 'created': return <Plus size={14} className="text-blue-500" />;
            case 'approved': return <CheckCircle2 size={14} className="text-emerald-500" />;
            case 'rejected': return <XCircle size={14} className="text-rose-500" />;
            case 'inspected': return <FileSearch size={14} className="text-amber-500" />;
            case 'open': return <Clock size={14} className="text-indigo-500" />;
            default: return <Circle size={14} className="text-slate-400" />;
        }
    };

    if (viewMode === 'UPDATE') return (
        <Paper sx={{ p: 4, borderRadius: 3 }} className="animate-in slide-in-from-right duration-300">
            <Box display="flex" justifyContent="space-between" mb={4} alignItems="center">
                <Box>
                    <Typography variant="h6" fontWeight="bold">Technical Inspection Request</Typography>
                    <Typography variant="caption" color="text.secondary">Project Quality Verification Form</Typography>
                </Box>
                <IconButton onClick={() => setViewMode('LIST')}><X /></IconButton>
            </Box>
            
            <Grid container spacing={3}>
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="Location (Chainage + Side)" 
                        placeholder="e.g. 12+400 RHS"
                        value={formData.location || ''} 
                        onChange={e => {
                            setFormData({...formData, location: e.target.value});
                            if (locationError) setLocationError(null);
                        }}
                        required
                        error={!!locationError}
                        helperText={locationError || "Format: [Km]+[Mtrs] [Side] e.g. 12+400 RHS"}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><MapPin size={18} className={locationError ? "text-rose-500" : "text-indigo-500"} /></InputAdornment>,
                        }}
                    />
                </Grid>
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="Request Number" 
                        placeholder="e.g. RFI-001"
                        value={requestNumber || ''} 
                        onChange={e => setRequestNumber(e.target.value)}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><FileText size={18} className="text-indigo-500" /></InputAdornment>,
                        }}
                    />
                </Grid>
                
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="Request Date" type="date" 
                        InputLabelProps={{ shrink: true }}
                        value={formData.date || ''} 
                        onChange={e => setFormData({...formData, date: e.target.value})} 
                    />
                </Grid>
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="Inspection Time" type="time" 
                        InputLabelProps={{ shrink: true }}
                        value={inspectionTime || ''} 
                        onChange={e => setInspectionTime(e.target.value)} 
                    />
                </Grid>
                
                <Grid item xs={12} md={6}>
                    <FormControl fullWidth>
                        <InputLabel>Inspection Purpose</InputLabel>
                        <Select 
                            value={inspectionPurpose} 
                            label="Inspection Purpose" 
                            onChange={e => setInspectionPurpose(e.target.value as 'First' | 'Second' | 'Third' | 'Routine' | 'Special')}
                        >
                            <MenuItem value="First">First Inspection</MenuItem>
                            <MenuItem value="Second">Second Inspection</MenuItem>
                            <MenuItem value="Third">Third Inspection</MenuItem>
                            <MenuItem value="Routine">Routine Inspection</MenuItem>
                            <MenuItem value="Special">Special Inspection</MenuItem>
                        </Select>
                    </FormControl>
                </Grid>
                <Grid item xs={12} md={6}>
                    <FormControl fullWidth>
                        <InputLabel>Update Status</InputLabel>
                        <Select 
                            value={formData.status || RFIStatus.OPEN} 
                            label="Update Status" 
                            onChange={e => setFormData({...formData, status: e.target.value as RFIStatus})}
                        >
                            <MenuItem value={RFIStatus.OPEN}>Open / Pending Inspection</MenuItem>
                            <MenuItem value={RFIStatus.APPROVED}>Approved / Verified</MenuItem>
                            <MenuItem value={RFIStatus.REJECTED}>Rejected / Rectification Needed</MenuItem>
                            <MenuItem value={RFIStatus.CLOSED}>Closed</MenuItem>
                        </Select>
                    </FormControl>
                </Grid>
                
                <Grid item xs={12}>
                    <TextField 
                        fullWidth multiline rows={4} label="Work Description for Inspection" 
                        placeholder="Define scope for verification (e.g. Reinforcement, GSB Layer, BC Mix)..."
                        value={formData.description || ''} 
                        onChange={e => setFormData({...formData, description: e.target.value})} 
                    />
                </Grid>
                
                <Grid item xs={12}>
                    <TextField 
                        fullWidth multiline rows={4} label="Inspection Report" 
                        placeholder="Record findings and observations from the inspection..."
                        value={inspectionReport || ''} 
                        onChange={e => setInspectionReport(e.target.value)} 
                    />
                </Grid>
                
                <Grid item xs={12}>
                    <TextField 
                        fullWidth multiline rows={3} label="Engineer's Representative Comments" 
                        placeholder="Add any comments or observations from the engineer..."
                        value={engineerComments || ''} 
                        onChange={e => setEngineerComments(e.target.value)} 
                    />
                </Grid>
                
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="ARE/IOW Signature" 
                        placeholder="Enter signature details"
                        value={areSignature || ''} 
                        onChange={e => setAreSignature(e.target.value)}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><UserIcon size={18} className="text-indigo-500" /></InputAdornment>,
                        }}
                    />
                </Grid>
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="ME/SLT Signature" 
                        placeholder="Enter signature details"
                        value={meSltSignature || ''} 
                        onChange={e => setMeSltSignature(e.target.value)}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><UserIcon size={18} className="text-indigo-500" /></InputAdornment>,
                        }}
                    />
                </Grid>
                
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="IOW Signature" 
                        placeholder="Enter signature details"
                        value={iowSignature || ''} 
                        onChange={e => setIowSignature(e.target.value)}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><UserIcon size={18} className="text-indigo-500" /></InputAdornment>,
                        }}
                    />
                </Grid>
                <Grid item xs={12} md={6}>
                    <TextField 
                        fullWidth label="RE Signature" 
                        placeholder="Enter signature details"
                        value={reSignature || ''} 
                        onChange={e => setReSignature(e.target.value)}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><UserIcon size={18} className="text-indigo-500" /></InputAdornment>,
                        }}
                    />
                </Grid>
                
                <Grid item xs={12} md={6}>
                    <Autocomplete
                        fullWidth
                        options={project.schedule}
                        getOptionLabel={(option) => option.name}
                        value={project.schedule.find(t => t.id === formData.linkedTaskId) || null}
                        onChange={(_, newValue) => setFormData({...formData, linkedTaskId: newValue?.id})}
                        renderOption={(props, option) => (
                            <li {...props}>
                                <Box width="100%">
                                    <Box display="flex" justifyContent="space-between">
                                        <Typography variant="body2" fontWeight="bold">{option.name}</Typography>
                                        <Chip label={`${option.progress}%`} size="small" sx={{ fontSize: 9, height: 16 }} />
                                    </Box>
                                    <Typography variant="caption" color="text.secondary">{option.startDate} to {option.endDate}</Typography>
                                </Box>
                            </li>
                        )}
                        renderInput={(params) => {
                            const { InputProps, ...rest } = params;
                            return (
                                <TextField 
                                    {...rest}
                                    label="Link to Schedule Task" 
                                    placeholder="Bind this inspection to an activity..."
                                    InputProps={{
                                        ...(InputProps as any),
                                        startAdornment: (
                                            <React.Fragment>
                                                <InputAdornment position="start"><LinkIcon size={18} className="text-indigo-600" /></InputAdornment>
                                                {InputProps.startAdornment}
                                            </React.Fragment>
                                        ),
                                    }}
                                />
                            );
                        }}
                    />
                </Grid>
                
                <Grid item xs={12}>
                    <TextField 
                        fullWidth label="Working Drawings Attachment" 
                        placeholder="Upload or reference working drawings"
                        value={workingDrawings.join(', ') || ''} 
                        onChange={e => setWorkingDrawings(e.target.value.split(',').map(item => item.trim()))}
                        InputProps={{
                            startAdornment: <InputAdornment position="start"><FileSearch size={18} className="text-indigo-500" /></InputAdornment>,
                        }}
                        helperText="Separate multiple drawing references with commas"
                    />
                </Grid>
            </Grid>

            <Box mt={4} display="flex" justifyContent="flex-end" gap={2}>
                <Button onClick={() => {setViewMode('LIST'); setFormData({});}}>Back</Button>
                <Button variant="contained" onClick={handleSave} startIcon={<CheckCircle2 size={18}/>}>Commit Audit Log</Button>
            </Box>
        </Paper>
    );

    return (
        <Box className="animate-in fade-in duration-500">
            <Box display="flex" justifyContent="space-between" mb={4} alignItems="center">
                <Box>
                    <Typography variant="h5" fontWeight="900">Technical Inspection Registry</Typography>
                    <Typography variant="body2" color="text.secondary">Verification of works against contract specifications</Typography>
                </Box>
                <Stack direction="row" spacing={2} alignItems="center">
                    <FormControl size="small" sx={{ minWidth: 220 }}>
                        <InputLabel>Filter by Activity</InputLabel>
                        <Select 
                            value={taskFilter} 
                            label="Filter by Activity" 
                            onChange={(e) => setTaskFilter(e.target.value)}
                            startAdornment={<InputAdornment position="start"><Filter size={14}/></InputAdornment>}
                            sx={{ bgcolor: 'background.paper', borderRadius: 2 }}
                        >
                            <MenuItem value="all">All Project Activities</MenuItem>
                            <Divider />
                            {project.schedule.map(task => (
                                <MenuItem key={task.id} value={task.id}>{task.name}</MenuItem>
                            ))}
                        </Select>
                    </FormControl>
                    <Button variant="contained" startIcon={<Plus />} onClick={handleCreate} sx={{ borderRadius: 2 }}>New RFI</Button>
                </Stack>
            </Box>

            <Grid container spacing={2} mb={4}>
                <Grid item xs={6} sm={3}>
                    <StatCard title="Open" value={statusCounts[RFIStatus.OPEN]} icon={Clock} color="#4f46e5" />
                </Grid>
                <Grid item xs={6} sm={3}>
                    <StatCard title="Approved" value={statusCounts[RFIStatus.APPROVED]} icon={CheckCircle} color="#10b981" />
                </Grid>
                <Grid item xs={6} sm={3}>
                    <StatCard title="Rejected" value={statusCounts[RFIStatus.REJECTED]} icon={XCircle} color="#f43f5e" />
                </Grid>
                <Grid item xs={6} sm={3}>
                    <StatCard title="Closed" value={statusCounts[RFIStatus.CLOSED]} icon={Lock} color="#64748b" />
                </Grid>
            </Grid>

            <Paper variant="outlined" sx={{ borderRadius: 4, overflow: 'hidden', bgcolor: 'background.paper' }}>
                <Table size="small">
                    <TableHead sx={{ bgcolor: 'action.hover' }}>
                        <TableRow>
                            <TableCell sx={{ fontWeight: 'bold' }}>Ref #</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Location</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Linked Activity</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Work Scope</TableCell>
                            <TableCell sx={{ fontWeight: 'bold' }}>Status</TableCell>
                            <TableCell align="right" sx={{ fontWeight: 'bold' }}>Actions</TableCell>
                        </TableRow>
                    </TableHead>
                    <TableBody>
                        {filteredRFIs.map((rfi, index) => {
                            const linkedTask = project.schedule.find(t => t.id === rfi.linkedTaskId);
                            return (
                                <TableRow key={rfi.id} hover sx={{ '&:nth-of-type(odd)': { bgcolor: 'action.hover' } }}>
                                    <TableCell sx={{ fontWeight: 'bold', color: 'primary.main', fontFamily: 'monospace' }}>{rfi.rfiNumber}</TableCell>
                                    <TableCell><Typography variant="body2" fontWeight="bold">{rfi.location}</Typography></TableCell>
                                    <TableCell>
                                        {linkedTask ? (
                                            <Tooltip title={`Task Progress: ${linkedTask.progress}%`}>
                                                <Box sx={{ minWidth: 140 }}>
                                                    <Typography variant="caption" fontWeight="bold" color="text.primary" display="block" sx={{ lineHeight: 1, mb: 0.5 }}>
                                                        {linkedTask.name}
                                                    </Typography>
                                                    <LinearProgress variant="determinate" value={linkedTask.progress} sx={{ height: 4, borderRadius: 2 }} />
                                                </Box>
                                            </Tooltip>
                                        ) : (
                                            <Typography variant="caption" color="text.disabled">—</Typography>
                                        )}
                                    </TableCell>
                                    <TableCell sx={{ maxWidth: 200 }}><Typography variant="caption" noWrap display="block">{rfi.description}</Typography></TableCell>
                                    <TableCell>
                                        <Chip label={rfi.status} size="small" variant="outlined" color={rfi.status === RFIStatus.APPROVED ? 'success' : rfi.status === RFIStatus.REJECTED ? 'error' : 'primary'} sx={{ fontWeight: '900', fontSize: 9 }} />
                                    </TableCell>
                                    <TableCell align="right">
                                        <Stack direction="row" spacing={0} justifyContent="flex-end" className="opacity-0 group-hover:opacity-100 transition-opacity">
                                            <IconButton size="small" onClick={() => { setSelectedRfiForDetail(rfi); setIsDetailModalOpen(true); }}><Eye size={16}/></IconButton>
                                            <IconButton size="small" onClick={() => handleEdit(rfi)}><Edit2 size={16}/></IconButton>
                                            <IconButton size="small" color="error" onClick={() => handleDelete(rfi.id)}><Trash2 size={16}/></IconButton>
                                        </Stack>
                                    </TableCell>
                                </TableRow>
                            );
                        })}
                        {filteredRFIs.length === 0 && (
                            <TableRow>
                                <TableCell align="center" {...{ colSpan: 6 }} sx={{ py: 10 }}>
                                    <Typography variant="body2" color="text.disabled">No inspection requests found for this filter.</Typography>
                                </TableCell>
                            </TableRow>
                        )}
                    </TableBody>
                </Table>
            </Paper>

            <Dialog open={isDetailModalOpen} onClose={() => setIsDetailModalOpen(false)} maxWidth="md" fullWidth PaperProps={{ sx: { borderRadius: 4 } }}>
                <DialogTitle sx={{ borderBottom: 1, borderColor: 'divider', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Box display="flex" alignItems="center" gap={1.5}>
                        <FileText size={24} color="primary.main"/>
                        <Box>
                            <Typography variant="h6" fontWeight="bold">Technical Inspection Report</Typography>
                            <Typography variant="caption" color="text.secondary">{selectedRfiForDetail?.rfiNumber}</Typography>
                        </Box>
                    </Box>
                    <IconButton onClick={() => setIsDetailModalOpen(false)}><X/></IconButton>
                </DialogTitle>
                <DialogContent sx={{ p: 0, bgcolor: 'background.default' }}>
                    {selectedRfiForDetail && (
                        <Grid container spacing={0}>
                            <Grid item xs={12} md={7} sx={{ p: 4, borderRight: '1px solid', borderColor: 'divider' }}>
                                <Stack spacing={4}>
                                    <Box>
                                        <Typography variant="caption" fontWeight="900" color="text.secondary" sx={{ letterSpacing: 1 }}>INSPECTION DESCRIPTION</Typography>
                                        <Paper variant="outlined" sx={{ p: 2, mt: 1.5, bgcolor: 'background.paper', borderRadius: 2 }}>
                                            <Typography variant="body2" sx={{ lineHeight: 1.6 }}>{selectedRfiForDetail.description}</Typography>
                                        </Paper>
                                    </Box>
                                    
                                    <Box>
                                        <Typography variant="caption" fontWeight="900" color="text.secondary" sx={{ letterSpacing: 1 }}>WORKFLOW AUDIT TRAIL</Typography>
                                        <Box mt={2.5}>
                                            {selectedRfiForDetail.workflowLog && selectedRfiForDetail.workflowLog.length > 0 ? (
                                                <Stack spacing={0}>
                                                    {selectedRfiForDetail.workflowLog.map((log, idx) => (
                                                        <Box key={idx} sx={{ display: 'flex', gap: 2, position: 'relative', pb: idx === selectedRfiForDetail.workflowLog!.length - 1 ? 0 : 3 }}>
                                                            {idx !== selectedRfiForDetail.workflowLog!.length - 1 && (
                                                                <Box sx={{ position: 'absolute', left: 15, top: 32, bottom: 0, width: '2px', bgcolor: 'divider' }} />
                                                            )}
                                                            
                                                            <Avatar sx={{ width: 32, height: 32, bgcolor: 'background.paper', border: '2px solid', borderColor: 'divider', zIndex: 1 }}>
                                                                {getStageIcon(log.stage)}
                                                            </Avatar>
                                                            
                                                            <Box flex={1}>
                                                                <Box display="flex" justifyContent="space-between" alignItems="center">
                                                                    <Typography variant="subtitle2" fontWeight="900" color="text.primary">{log.stage.toUpperCase()}</Typography>
                                                                    <Typography variant="caption" color="text.secondary" sx={{ fontFamily: 'monospace' }}>
                                                                        {new Date(log.timestamp).toLocaleString([], { dateStyle: 'short', timeStyle: 'short' })}
                                                                    </Typography>
                                                                </Box>
                                                                <Typography variant="caption" display="block" color="primary.main" fontWeight="bold">
                                                                    Action by: {log.user}
                                                                </Typography>
                                                                {log.comments && (
                                                                    <Typography variant="body2" color="text.secondary" sx={{ bgcolor: 'background.paper', p: 1, borderRadius: 1, border: '1px solid', borderColor: 'divider', mt: 0.5 }}>
                                                                        {log.comments}
                                                                    </Typography>
                                                                )}
                                                            </Box>
                                                        </Box>
                                                    ))}
                                                </Stack>
                                            ) : (
                                                <Typography variant="caption" color="text.disabled" fontStyle="italic">No history recorded.</Typography>
                                            )}
                                        </Box>
                                    </Box>
                                </Stack>
                            </Grid>

                            <Grid item xs={12} md={5} sx={{ p: 4, bgcolor: 'action.hover' }}>
                                <Stack spacing={3}>
                                    <Box>
                                        <Typography variant="caption" fontWeight="900" color="text.secondary" sx={{ letterSpacing: 1 }}>LOCATION / CHAINAGE</Typography>
                                        <Typography variant="h6" fontWeight="bold" display="flex" alignItems="center" gap={1} sx={{ mt: 1 }}>
                                            <MapPin size={18} color="primary.main"/> {selectedRfiForDetail.location}
                                        </Typography>
                                    </Box>

                                    <Divider />

                                    <Box>
                                        <Typography variant="caption" fontWeight="900" color="text.secondary" display="block" mb={1.5} sx={{ letterSpacing: 1 }}>CURRENT STATUS</Typography>
                                        <Chip 
                                            label={selectedRfiForDetail.status.toUpperCase()} 
                                            color={selectedRfiForDetail.status === RFIStatus.APPROVED ? 'success' : selectedRfiForDetail.status === RFIStatus.REJECTED ? 'error' : 'primary'} 
                                            sx={{ fontWeight: 'bold', height: 40, borderRadius: 2, width: '100%' }} 
                                        />
                                    </Box>

                                    <Paper variant="outlined" sx={{ p: 2.5, borderRadius: 3, bgcolor: 'background.paper' }}>
                                        <Typography variant="caption" fontWeight="900" color="text.secondary" display="flex" alignItems="center" gap={1} mb={1.5}>
                                            <BarChart2 size={14}/> SCHEDULE CONTEXT
                                        </Typography>
                                        {project.schedule.find(t => t.id === selectedRfiForDetail.linkedTaskId) ? (
                                            <Box>
                                                <Typography variant="body2" fontWeight="bold">{project.schedule.find(t => t.id === selectedRfiForDetail.linkedTaskId)?.name}</Typography>
                                                <Box display="flex" justifyContent="space-between" mt={1}>
                                                    <Typography variant="caption" color="text.secondary">Task Progress</Typography>
                                                    <Typography variant="caption" fontWeight="bold">{project.schedule.find(t => t.id === selectedRfiForDetail.linkedTaskId)?.progress}%</Typography>
                                                </Box>
                                                <LinearProgress 
                                                    variant="determinate" 
                                                    value={project.schedule.find(t => t.id === selectedRfiForDetail.linkedTaskId)?.progress || 0} 
                                                    sx={{ height: 6, mt: 0.5, borderRadius: 3 }} 
                                                />
                                            </Box>
                                        ) : (
                                            <Typography variant="caption" color="text.disabled" fontStyle="italic">Not linked to a schedule task.</Typography>
                                        )}
                                    </Paper>
                                    
                                    <Button fullWidth variant="contained" startIcon={<Printer/>} onClick={() => window.print()} sx={{ mt: 2, height: 48, borderRadius: 2 }}>Print Certificate</Button>
                                </Stack>
                            </Grid>
                        </Grid>
                    )}
                </DialogContent>
            </Dialog>
        </Box>
    );
};

export default RFIModule;
