#!/bin/bash
# BOQ Persistence Diagnostic Guide
# 
# This script guides you through testing BOQ persistence
# Run all steps and share the console output

echo "=========================================="
echo "BOQ PERSISTENCE DIAGNOSTIC"
echo "=========================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1. OPEN BROWSER DEVELOPER TOOLS"
echo "   - Press F12"
echo "   - Go to Console tab"
echo "   - Keep it open while testing"
echo ""
echo "2. CREATE/ADD BOQ ITEMS"
echo "   - Go to a project"
echo "   - Open BOQ tab"
echo "   - Add a new BOQ item"
echo "   - Click Save"
echo "   - WATCH THE CONSOLE for [BOQ DEBUG] messages"
echo ""
echo "3. LOOK FOR THESE DEBUG MESSAGES:"
echo "   ✓ [BOQ DEBUG] handleSaveNewItem - saving to project"
echo "   ✓ [BOQ DEBUG] sanitizeProjectForApi input/output"
echo "   ✓ [BOQ DEBUG] updateProject - BOQ data (BEFORE request)"
echo "   ✓ [BOQ DEBUG] updateProject response - BOQ data (AFTER request)"
echo ""
echo "4. CLOSE AND REOPEN BROWSER"
echo "   - Close ALL tabs"
echo "   - Reopen the app"
echo "   - Open the SAME project"
echo "   - Go to BOQ tab"
echo "   - WATCH THE CONSOLE for:"
echo "     ✓ [BOQ DEBUG] getProjects response"
echo "     ✓ [BOQ DEBUG] BOQRegistry component render"
echo ""
echo "5. SHARE THIS INFORMATION:"
echo "   - Copy ALL console messages starting with [BOQ DEBUG]"
echo "   - Note if the BOQ item APPEARS after reload"
echo "   - Note any error messages"
echo ""
echo "=========================================="
echo ""
